{"name": "test_invalid_username", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert False == True\n +  where False = validate_username('invalid@user')", "trace": "@pytest.mark.xfail\n    def test_invalid_username():\n>       assert validate_username(\"invalid@user\") == True  # This will fail\nE       AssertionError: assert False == True\nE        +  where False = validate_username('invalid@user')\n\ntest_model.py:64: AssertionError"}, "start": 1735881307617, "stop": 1735881307617, "uuid": "3145f6b0-22ad-47a6-96f3-e5b93bed508b", "historyId": "cbf0f3eca34253f987a53ebc7dc25aa3", "testCaseId": "cbf0f3eca34253f987a53ebc7dc25aa3", "fullName": "test_model#test_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_model"}, {"name": "host", "value": "C16622"}, {"name": "thread", "value": "64894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_model"}]}